// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import CategoriesController from "./categories_controller.js";
application.register("categories", CategoriesController);

import TagsController from "./tags_controller";
application.register("tags", TagsController);

import MilkdownController from "./milkdown_controller.js";
application.register("milkdown", MilkdownController);

import CodeCopyController from "./code_copy_controller.js";
application.register("code-copy", CodeCopyController);
