inherit_gem:
  rubocop-rails-omakase: rubocop.yml

require:
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false

# Enable ERB Lint
Rails/RenderInline:
  Enabled: true

# Configure ERB Lint
Rails/ErbSafety:
  Enabled: true

# Enable Rails cops
Rails:
  Enabled: true
