default: &default
  common_tags:
    - javascript
    - ruby
    - rails
    - react
    - vue
    - angular
    - typescript

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
